In [1]:
from sklearn import linear_model
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv("./annual_csv.csv",sep=",")
data_to_numpy = data.values

In [30]:
data.head

<bound method NDFrame.head of      Year    GCAG  GISTEMP
0    1880 -0.1148    -0.20
1    1881 -0.0628    -0.12
2    1882 -0.0648    -0.10
3    1883 -0.1424    -0.21
4    1884 -0.2009    -0.28
5    1885 -0.2125    -0.32
6    1886 -0.2003    -0.31
7    1887 -0.2489    -0.33
8    1888 -0.1471    -0.20
9    1889 -0.0982    -0.12
10   1890 -0.3220    -0.37
11   1891 -0.2532    -0.24
12   1892 -0.3062    -0.27
13   1893 -0.3212    -0.30
14   1894 -0.2808    -0.31
15   1895 -0.2290    -0.21
16   1896 -0.0974    -0.15
17   1897 -0.1224    -0.11
18   1898 -0.2546    -0.28
19   1899 -0.1173    -0.16
20   1900 -0.0679    -0.09
21   1901 -0.1417    -0.15
22   1902 -0.2463    -0.27
23   1903 -0.3369    -0.35
24   1904 -0.4194    -0.44
25   1905 -0.2931    -0.28
26   1906 -0.2174    -0.23
27   1907 -0.3706    -0.40
28   1908 -0.4396    -0.43
29   1909 -0.4261    -0.47
..    ...     ...      ...
107  1987  0.3696     0.33
108  1988  0.3757     0.41
109  1989  0.2970     0.29
110  1990  0.4328     0.4

In [4]:
data_to_numpy

array([[  1.88000000e+03,  -1.14800000e-01,  -2.00000000e-01],
       [  1.88100000e+03,  -6.28000000e-02,  -1.20000000e-01],
       [  1.88200000e+03,  -6.48000000e-02,  -1.00000000e-01],
       [  1.88300000e+03,  -1.42400000e-01,  -2.10000000e-01],
       [  1.88400000e+03,  -2.00900000e-01,  -2.80000000e-01],
       [  1.88500000e+03,  -2.12500000e-01,  -3.20000000e-01],
       [  1.88600000e+03,  -2.00300000e-01,  -3.10000000e-01],
       [  1.88700000e+03,  -2.48900000e-01,  -3.30000000e-01],
       [  1.88800000e+03,  -1.47100000e-01,  -2.00000000e-01],
       [  1.88900000e+03,  -9.82000000e-02,  -1.20000000e-01],
       [  1.89000000e+03,  -3.22000000e-01,  -3.70000000e-01],
       [  1.89100000e+03,  -2.53200000e-01,  -2.40000000e-01],
       [  1.89200000e+03,  -3.06200000e-01,  -2.70000000e-01],
       [  1.89300000e+03,  -3.21200000e-01,  -3.00000000e-01],
       [  1.89400000e+03,  -2.80800000e-01,  -3.10000000e-01],
       [  1.89500000e+03,  -2.29000000e-01,  -2.1000000

In [31]:
x = data_to_numpy[:,0]
y_GCAG = data_to_numpy[:,1]

In [32]:
regr = linear_model.Lasso()
regr.fit(x[75:,np.newaxis], y_GCAG[75:])

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [33]:
x_test = np.arange(2017,2051)

In [34]:
predict = regr.predict(x_test[:,np.newaxis])

In [35]:
predict

array([ 0.653611  ,  0.66502492,  0.67643884,  0.68785275,  0.69926667,
        0.71068059,  0.72209451,  0.73350843,  0.74492234,  0.75633626,
        0.76775018,  0.7791641 ,  0.79057802,  0.80199193,  0.81340585,
        0.82481977,  0.83623369,  0.84764761,  0.85906152,  0.87047544,
        0.88188936,  0.89330328,  0.9047172 ,  0.91613111,  0.92754503,
        0.93895895,  0.95037287,  0.96178679,  0.97320071,  0.98461462,
        0.99602854,  1.00744246,  1.01885638,  1.0302703 ])

In [36]:
y_GISTEMP = data_to_numpy[:,2]

In [37]:
regr_GISTEMP = linear_model.Lasso()
regr_GISTEMP.fit(x[75:,np.newaxis], y_GISTEMP[75:])

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [38]:
predict_GISTEMP = regr_GISTEMP.predict(x_test[:,np.newaxis])

In [39]:
predict_GISTEMP

array([ 0.66500793,  0.67715872,  0.68930951,  0.7014603 ,  0.71361109,
        0.72576188,  0.73791267,  0.75006346,  0.76221425,  0.77436504,
        0.78651583,  0.79866662,  0.81081741,  0.8229682 ,  0.83511898,
        0.84726977,  0.85942056,  0.87157135,  0.88372214,  0.89587293,
        0.90802372,  0.92017451,  0.9323253 ,  0.94447609,  0.95662688,
        0.96877767,  0.98092846,  0.99307925,  1.00523004,  1.01738083,
        1.02953162,  1.04168241,  1.05383319,  1.06598398])

In [41]:
for i in range(len(x_test)):
    data_to_numpy = np.vstack([data_to_numpy,[x_test[i],predict[i],predict_GISTEMP[i]]])

In [42]:
data_to_numpy

array([[  1.88000000e+03,  -1.14800000e-01,  -2.00000000e-01],
       [  1.88100000e+03,  -6.28000000e-02,  -1.20000000e-01],
       [  1.88200000e+03,  -6.48000000e-02,  -1.00000000e-01],
       [  1.88300000e+03,  -1.42400000e-01,  -2.10000000e-01],
       [  1.88400000e+03,  -2.00900000e-01,  -2.80000000e-01],
       [  1.88500000e+03,  -2.12500000e-01,  -3.20000000e-01],
       [  1.88600000e+03,  -2.00300000e-01,  -3.10000000e-01],
       [  1.88700000e+03,  -2.48900000e-01,  -3.30000000e-01],
       [  1.88800000e+03,  -1.47100000e-01,  -2.00000000e-01],
       [  1.88900000e+03,  -9.82000000e-02,  -1.20000000e-01],
       [  1.89000000e+03,  -3.22000000e-01,  -3.70000000e-01],
       [  1.89100000e+03,  -2.53200000e-01,  -2.40000000e-01],
       [  1.89200000e+03,  -3.06200000e-01,  -2.70000000e-01],
       [  1.89300000e+03,  -3.21200000e-01,  -3.00000000e-01],
       [  1.89400000e+03,  -2.80800000e-01,  -3.10000000e-01],
       [  1.89500000e+03,  -2.29000000e-01,  -2.1000000

In [44]:
data_to_numpy=data_to_numpy[data_to_numpy[:,0]>=1950]

In [45]:
data_to_numpy

array([[  1.95000000e+03,  -1.61600000e-01,  -1.80000000e-01],
       [  1.95100000e+03,  -1.32000000e-02,  -7.00000000e-02],
       [  1.95200000e+03,   2.48000000e-02,   1.00000000e-02],
       [  1.95300000e+03,   9.52000000e-02,   8.00000000e-02],
       [  1.95400000e+03,  -1.16500000e-01,  -1.30000000e-01],
       [  1.95500000e+03,  -1.35400000e-01,  -1.50000000e-01],
       [  1.95600000e+03,  -1.99000000e-01,  -2.00000000e-01],
       [  1.95700000e+03,   4.88000000e-02,   4.00000000e-02],
       [  1.95800000e+03,   1.09500000e-01,   7.00000000e-02],
       [  1.95900000e+03,   5.96000000e-02,   3.00000000e-02],
       [  1.96000000e+03,   2.04000000e-02,  -2.00000000e-02],
       [  1.96100000e+03,   7.75000000e-02,   5.00000000e-02],
       [  1.96200000e+03,   8.88000000e-02,   3.00000000e-02],
       [  1.96300000e+03,   1.06800000e-01,   6.00000000e-02],
       [  1.96400000e+03,  -1.49500000e-01,  -2.00000000e-01],
       [  1.96500000e+03,  -7.80000000e-02,  -1.0000000

In [46]:
np.savetxt("./rechauffement_clim.csv",data_to_numpy,delimiter=',')